ci: watcher for automerge
google/python-fire pull request #435
Opened 2023-02-02 10:31 UTC by Borda

As discussed in https://github.com/google/python-fire/pull/428#issuecomment-1413497193 adding a closure job would allow enabling automerge without need of updating branch protection checks when new Python version is added

2023-02-02 13:45 UTC, Borda commented
now we could set these two as required checks: 
![image](https://user-images.githubusercontent.com/6035284/216341529-a5bd2e66-ab1c-40ca-b7f6-3b66dc2ca7a5.png)

2023-02-02 15:31 UTC, hugovk commented
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1324225/216368162-9741b7e1-1505-4ee3-919b-0b8403ec1f2f.png">

👍

2023-02-02 15:34 UTC, hugovk requested changes

2023-02-02 15:34 UTC, hugovk commented on .github/workflows/build.yml
> +    branches: [master]
This is unfriendly to contribution.

People should contribute using [feature branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches), and we should allow people to test their work on their fork before opening a PR.

```suggestion
on: [push, pull_request]
```

2023-02-02 17:47 UTC, hugovk approved these changes
👍

2023-02-07 00:56 UTC, Borda commented
@dbieber any idea what is happening with the @copybara? as there are no details shared... :thinking:

2023-02-07 15:42 UTC, dbieber commented
Copybara is the tool we use to sync the google internal copy of the repo with the github copy. The error could be from them getting out of sync; I'll have to look into that. You can ignore that check in the mean time.

2023-02-20 18:54 UTC, Borda commented
@dbieber how is it going? :chipmunk:

2023-03-07 14:52 UTC, Borda commented
@dbieber can I help with anything else here? :rabbit:

2023-03-07 15:16 UTC, dbieber commented
Thanks for checking back in, but unfortunately no, no updates on my end.

2023-04-20 18:51 UTC, Borda commented
hello @dbieber, any update so far? :flamingo:

2023-06-02 17:47 UTC, Borda commented
HOw is it going @dbieber :flamingo:

2023-07-06 21:46 UTC, Borda commented
@dbieber, any chance you could check it? :rabbit:

2023-09-19 12:36 UTC, Borda commented
@dbieberhow are you doing, still with this project? :chipmunk:

2024-01-02 20:38 UTC, Borda commented
hello @dbieber, happy New year! :fireworks:

2024-01-09 17:36 UTC, Borda commented
@dbieber any chance to get some more details on what is happening with the `copybara`?

2024-01-09 18:10 UTC, dbieber commented
> @dbieber any chance to get some more details on what is happening with the `copybara`?

Hmm, I don't know offhand. Copybara is a tool we use to sync our internal and external codebases. I'll have to investigate.

2024-01-09 18:12 UTC, Borda commented
> I'll have to investigate.

lets try just restart it for now?

2024-01-09 18:19 UTC, dbieber commented
You can safely ignore it.

2024-01-09 18:22 UTC, Borda commented
> You can safely ignore it.

the rest is green :green_circle:

2024-02-08 14:12 UTC, Borda commented
@dbieber, so can we merge it? :thinking:

2024-02-24 20:20 UTC, dbieber commented
Hi Borda,

Thank you for the PR and your patience. I see the value of running the GitHub Actions on a pull_request. I do not see the value of the watcher job or auto-merge, however.

I understand that the watcher job would allow for auto-merge. Perhaps I am misunderstanding what auto-merge is, but it seems to me that I would like to review and approve PRs before they are merged, and hence I do not want to enable auto-merge on this project. Let me know if I'm misunderstanding auto-merge or missing something.

Cheers,
David 

🐙

2024-02-24 20:56 UTC, Borda commented
> I understand that the watcher job would allow for auto-merge.

That is probably a misunderstanding; the watcher jobs just aggregated the result over the previously completed matrix of jobs... so the case is that in the GH setting you do not need to click all jobs one by one and if you change Python version it need to be also updated in the setting but you set as required only this one which is aggregated result of all

2024-04-26 12:17 UTC, Borda commented
@dbieber, mind having a look and sharing your thoughts? 🦩
this will also be even more useful if we extend the testing matrix, ref #490

2024-07-14 13:43 UTC, Borda commented
@dbieber friendly ping if you could have a look... :chipmunk:

2024-09-22 17:58 UTC, Borda commented on .github/workflows/build.yml
> +
```suggestion
```

2024-09-22 18:00 UTC, Borda commented
@dbieber after the extended build matrix this gain its value as so safety you can set this watcher as required check and so all builds are required but without the need to name them one by one...

2024-10-07 10:38 UTC, Borda commented
> @dbieber after the extended build matrix this gain its value as so safety you can set this watcher as required check and so all builds are required but without the need to name them one by one...

mind check this one, and also add this rather to required checks?

2025-02-11 12:23 UTC, Borda commented
@dbieber friendly ping if we shall land it or close it? :)

2025-02-19 11:40 UTC, closed without merging